config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}  
  
  root to: 'users#index'  


  get 'sample_user', to: 'users#sample'     # it's not in resources since we don't have an id when selecting
  get 'users/get_by_ids' => 'users#get_by_ids'
  get 'lists/own'

  resources :users do

        member do   # member is for passing :id instead of :user_id
          get   'print' #,  to: 'users#print',  as: 'print'
          get   'copy'  #,  to: 'users#edit',   as: 'copy'
        end

        resources :mailgroups do      
          patch 'append',    to: 'users#append',  on: :collection    # append a MAILGROUP to a user
          member do
            delete 'remove', to: 'mailgroups#remove'
          end
        end

  end



  resources :mailgroups do

    member do
      get 'mailto'
      get 'print'
    end

    collection do
      get   'search_for', to: 'mailgroups#search_for',  as: 'search'
    end

    resources :users do
      patch 'append',     to: 'mailgroups#append', on: :collection   # append a USER to a mailgroup
      member do
        delete 'remove',  to: 'users#remove'    # remove USER from a mailgroup
      end
    end

  end


  resources :lists do

    resources :mailgroups do      
      patch 'append',     to: 'lists#append',  on: :collection    # append a MAILGROUP to a user
      member do  
        delete 'remove',  to: 'mailgroups#remove_list'
      end
    end

  end


  resources :intlists,      path: :lists,      controller: :list
  resources :intmailgroups, path: :mailgroups, controller: :mailgroups











end

app/models/list.rb
class List < ActiveRecord::Base

  has_and_belongs_to_many :mailgroups

  validates :name, uniqueness: true
  validates :email_id, uniqueness: true

  has_one :mailgroup, as: :robinson

  scope :own,     -> { where(admin: $LOGINNAME) }
  scope :regular, -> { where('query is NULL') }


  # this no good
  #has_many :mailgroups
  #has_many :users, through: :mailgroups

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  require 'application_helper'
  before_action :authenticate, except: [:index, :show, :choose]
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.regular
    @intlists = Intlist.all
    
    if $LOGINNAME
      @carboncopy="cc=#{$LOGINNAME}&"
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    logger.debug "@lc = #{@lc}"
    if $LOGINNAME
      @carboncopy="cc=#{$LOGINNAME}&"
    end
    list_count
  end

  # GET /lists/new
  def new
    @list = List.new
    @list.admin = current_user.login
  end



  # GET /lists/1/edit
  def edit
    unless list_admin?(@list)
      redirect_to @list, alert: 'You are not the list admin.'
    end
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    @query = get_query(params) # helpers/application_helper.rb
    logger.debug "in def update, query=#{@query}"
    if @query.present?
      @list = @list.becomes!(Intlist)
      @list.query = @query
    else
      @list = @list.becomes!(List)
    end
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def choose
    @userid = params[:user_id]
    @lists = List.all
  end


  # append a MAILGROUP to a LIST
  def append
    @mailgroup = Mailgroup.find(params[:mailgroup_id])  # this param comes from hidden tag, not from url!
    @list = List.find(params[:list_id])
    respond_to do |format|
      if @mailgroup.lists.append(@list)   # this is a collection-proxy method  ::  http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-append
        format.html { redirect_to @list, notice: 'Mailgroup was successfully added.' }
        format.json { render :show, status: :created, location: @list }
        format.js
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def own
    @lists = List.own
    @intlists = Intlist.own
    # respond_to do |format|
    #   format.json
    # end
    render :index
  end


  def sync_list
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      if params.has_key? :intlist
        params[:list] = params.delete :intlist
      end
      params.require(:list).permit(:name, :email_id, :memo, :admin, :query)
    end


    def list_count
      @lc = 0
      logger.debug ("in controller list, query = #{@list.query}")
      @list.mailgroups.each do |m|
        @lc += m.users.count(:id)
      end
    end


end


app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, html: { class: "form-horizontal list" } do |f| %>

    <% if @list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group row">
    <%= f.label :id, class: 'control-label col-lg-1 dim' %>
    <div class="controls col-lg-4">
      <%= f.text_field :id, class: 'form-control', readonly: true %>
    </div>
    <%= error_span(@list[:id]) %>
  </div>

  <div class="control-group row">
    <%= f.label :name, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-4">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%= error_span(@list[:name]) %>
  </div>

  <div class="control-group row">
    <%= f.label :email_id, class: 'control-label col-lg-1' %>
    <div class="controls input-group col-lg-4">
      <%= f.text_field :email_id, class: 'form-control addon' %>
      <span class="input-group-addon" id="basic-addon2">@sakk.ch</span>
    </div>
    <%= error_span(@list[:email_id]) %>
  </div>

  <div class="control-group row">
    <%= f.label :admin, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-4">
      <%= f.text_field :admin, class: 'form-control' %>
    </div>
    <%= error_span(@list[:admin]) %>
  </div>

  <div class="control-group row">
    <%= f.label :query, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-4">
      <%= f.text_field :query, class: 'form-control' %>
    </div>
    <%= error_span(@list[:query]) %>
  </div>

  <div class="control-group row">
    <%= f.label :type, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-4">
      <%= f.text_field :type, class: 'form-control' %>
    </div>
    <%= error_span(@list[:type]) %>
  </div>


  <%= f.submit "Update list", class: 'btn btn-primary spacer-medium' %>
  <%= link_to t('.cancel', default: t("helpers.links.cancel")),
            :back, class: 'btn btn-default spacer-medium' %>

<% end %>

<p class='iv'><%= "#{__FILE__}" %></p>

app/views/lists/_grouplist.html.erb
<!-- No loop is needed when rendering this partial -->

<%= content_tag_for(:tr, list) do %>
  <td class="dim"><%= list.id %></td>
  <td><%= list.name %></td>
  <td>

    <!-- %= link_to(content_tag(:i, nil, class: 'fa fa-pencil'), edit_list_path(list),
          data: {toggle: "tooltip", title: "Edit list", placement: 'top'}) if mutation?
     % -->

    <%= link_to(content_tag(:i, nil, class: 'fa fa-group loaderlink' ), list_path(list),
          data: {toggle: "tooltip", title: "List details and assigned groups", placement: 'top'})
     %>

  </td>
<% end %>

app/views/lists/_list.html.erb
<!-- No loop is needed when rendering this partial -->

<%= content_tag_for(:tr, list) do %>

  <td class="dim"><%= list.id %></td>
  <td><%= list.name %></td>
  <td><%= list.email_id %></td>
  <td><%= list.admin %></td>
  <td class="fadeactions col-md-2">

    <%= link_to(content_tag(:i, nil, class: 'fa fa-group loaderlink' ), list_path(list),
          data: {toggle: "tooltip", title: "List details and assigned groups", placement: 'top'})
     %>


    <%= link_to content_tag(:i, nil, class: 'fa fa-table'),
          "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+LIST+LIST&rs:Command=Render&rs:Format=Excel&listname=#{list.email_id}",
          data: {toggle: "tooltip", title: "Excel list", placement: 'top'}
     %>


    <%= link_to(content_tag(:i, nil, class: 'fa fa-envelope-o'),
          "mailto:#{list.email_id}@sakk.ch?#{@carboncopy}subject=<password> <your subject>&body=ATTENTION:The subject line is important! Mail is sent to all recipients of list. Type your message here",
          data: {toggle: "tooltip", title: "Email to", placement: 'top'})  %>


    <%= link_to(content_tag(:i, nil, class: 'fa fa-pencil'), edit_list_path(list),
          data: {toggle: "tooltip", title: "Edit list", placement: 'top'}) if list_admin?(list)
     %>


    <%= link_to(content_tag(:i, nil, class: 'fa fa-trash-o'),
                list_path(list),
                method: :delete,
                remote: true,
                data: { confirm: "Sure to delete #{list.name} ?",
                        toggle: "tooltip", title: "Delete list", placement: 'top'
                  })  if list_admin?(list)
    %> 


    <%= link_to(content_tag(:i, nil, class: 'fa fa-minus-square-o'),
        remove_list_mailgroup_path(@list, mailgroup),
          method: :delete,
          remote: true,
          data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')),
            toggle: "tooltip", title: "Remove mailgroup from list", placement: 'top'
          }) if defined? @list and list_admin?(list)
     %>

  </td>
<% end %>

app/views/lists/edit.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><!--%=t '.title', default: [:'helpers.titles.edit', '%{model}'], model: model_class.model_name.human.titleize % -->
  <%= @list.name %>
  <%= content_tag(:i, nil, class: 'fa fa-pencil') %>
  </h1>
</div>

<%= render partial: 'form' %>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/lists/index.html.erb
<%- model_class = List -%>



<div class="col-lg-12 row">
  <div class="page-header col-lg-2">
    <h1>Lists</h1>
  </div>


  <div class="col-lg-1 spacer-button">
    <%= link_to 'New List',
                new_list_path,
                class: 'btn btn-primary' if mutation?
     %>
  </div>

  <div class="col-lg-1 spacer-button" data-toggle="button" aria-pressed="false" autocomplete="off">
    <%= link_to 'Show my lists only',
                lists_own_path,
                method: 'get',
                class: 'btn btn-primary' if mutation?
     %>
  </div>
</div>


<table class="table table-striped fadeactions col-lg-12">
  <col width="5%"  />
  <col width="30%" />
  <col width="10%" />
  <col width="5%" />
  <col width="40%" />  
  <col width="10%" />  
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email_id) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%= model_class.human_attribute_name(:query) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% if params[:action] != 'own' %>
      <tr><td colspan="6"><h3>Regular lists</h3></td></tr>
      <%= render partial: @lists.order("name") %>
      <tr><td colspan="6"><h3>Intelligent lists</h3></td></tr>
      <%= render partial: @intlists.order("name")  %>
    <% else %>
      <tr><td colspan="6"><h3>My lists</h3></td></tr>
      <%= render partial: @lists.order("name") %>
    <% end %>  
  </tbody>
</table>


<div class="col-lg-2 spacer-button">
  <%= link_to 'New List',
              new_list_path,
              class: 'btn btn-primary' if mutation?
   %>
</div>


<%= content_tag(:div, "partial lists/_list" , class: 'iv col-lg-12') %>
<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/lists/new.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/lists/show.html.erb
<%- model_class = List -%>
<div class="page-header col-lg-12">
  <!-- h1><%=t '.title', default: model_class.model_name.human.titleize %></h1 -->
  <h1><%= content_tag(:i, nil, class: 'fa fa-list') %>
    <span class="dim"></span><%= "#{@list.name}" %> 
  </h1>

</div>

<!-- dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @list.name %></dd>
</dl -->

 <div class="panel panel-default panel-body col-lg-6">
    <h3>List details</h3>
    <dl class="dl-horizontal">
      <dt class="dim"><strong ><%= model_class.human_attribute_name(:id) %>:</strong></dt>
      <dd class="dim"><%= @list.id %></dd>
      <dt><strong>Email</strong></dt>
      <dd><%= "#{@list.email_id}@sakk.ch" %></dd>
      <dt><strong># Groups:</strong></dt>
      <dd><%= @list.mailgroups.count unless @list.mailgroups.nil? %></dd>
      <dt><strong># Users with Email:</strong></dt>
      <dd><%= @lc unless @list.mailgroups.nil? %></dd>
      <dt><strong>Admin:</dt></strong>
      <dd><%= @list.admin %></dd>
      <dt><strong>Query:</dt></strong>
      <dd><%= @list.query %></dd>
      <!-- dt><strong>Type:</dt></strong>
      <dd><%= @list.type if @list.query? %></dd -->
      <dt class="dim"><strong><%= model_class.human_attribute_name(:created_at) %>:</strong></dt>
      <dd class="dim"><%= @list.created_at.try(:to_formatted_s).try(:first,16) %></dd>
      <dt class="dim"><strong><%= model_class.human_attribute_name(:updated_at) %>:</strong></dt>
      <dd class="dim"><%= @list.updated_at.try(:to_formatted_s).try(:first,16) %></dd>
    </dl>
    <div class='panel-btn-group row'>


    <%= link_to content_tag(:i, nil, class: "fa fa-chevron-left") + 'Back',
                :back, class: 'btn btn-default spacer-medium'
     %>

    <%= link_to content_tag(:i, nil, class: "fa fa-pencil") + 'Edit',
                edit_list_path(@list), class: 'btn btn-default spacer-medium' if (mutation? == @list.admin)
     %>


    <%= link_to content_tag(:i, nil, class: 'fa fa-envelope-o') + "Mass mail",
          "mailto:#{@list.email_id}@sakk.ch?#{@carboncopy}subject=<password> <your subject>&body=ATTENTION:The subject line is important! Mail is sent to all recipients of list.      Type your message here",
          data: {toggle: "tooltip", title: "Mass mail to all members of this list", placement: 'top'},
          class: 'btn btn-default spacer-medium'
     %>


    <%= link_to_if @list.id==1, content_tag(:i, nil, class: 'fa fa-file-text') + "Addresslist",
          "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+LIST+KREBSBULLETIN&rs:Command=Render&rs:Format=CSV-semiq&ListID=#{@list.id}",
          data: {toggle: "tooltip", title: "Excel List for Krebsbulletin", placement: 'top'},
          class: 'btn btn-default spacer-medium' do
          end
     %>

    <%= link_to content_tag(:i, nil, class: 'fa fa-trash-o') + 'Delete',
            list_path(@list),
            method: 'delete',
            data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
            class: 'btn btn-danger spacer-medium' if list_admin?(@list)
     %>

    </div>

  </div>


  <% unless @list.mailgroup.nil? %>
    <div class="panel panel-default panel-body col-lg-offset-1 col-lg-5">
      <h3>Robinson group</h3>
      <dl class="dl-horizontal">
        <dt class="dim"><strong ><%= model_class.human_attribute_name(:id) %>:</strong></dt>
        <dd class="dim"><%= @list.mailgroup.id %></dd>
        <dt>Group name:</dt>
        <dd><%= @list.mailgroup.name %></dd>
      </dl>
     <%= link_to content_tag(:i, nil, class: "fa fa-group left") + 'Group details',
                mailgroup_path(@list.mailgroup), class: 'btn btn-default spacer-medium'
      %>
    </div>
  <% end %>


<%= render partial: "mailgroups/list_mailgroups" %>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>