config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}  
  
  root to: 'users#index'  


  get 'sample_user', to: 'users#sample'     # it's not in resources since we don't have an id when selecting
  get 'users/get_by_ids' => 'users#get_by_ids'
  get 'lists/own'

  resources :users do

        member do   # member is for passing :id instead of :user_id
          get   'print' #,  to: 'users#print',  as: 'print'
          get   'copy'  #,  to: 'users#edit',   as: 'copy'
        end

        resources :mailgroups do      
          patch 'append',    to: 'users#append',  on: :collection    # append a MAILGROUP to a user
          member do
            delete 'remove', to: 'mailgroups#remove'
          end
        end

  end



  resources :mailgroups do

    member do
      get 'mailto'
      get 'print'
    end

    collection do
      get   'search_for', to: 'mailgroups#search_for',  as: 'search'
    end

    resources :users do
      patch 'append',     to: 'mailgroups#append', on: :collection   # append a USER to a mailgroup
      member do
        delete 'remove',  to: 'users#remove'    # remove USER from a mailgroup
      end
    end

  end


  resources :lists do

    resources :mailgroups do      
      patch 'append',     to: 'lists#append',  on: :collection    # append a MAILGROUP to a user
      member do  
        delete 'remove',  to: 'mailgroups#remove_list'
      end
    end

  end


  resources :intlists,      path: :lists,      controller: :list
  resources :intmailgroups, path: :mailgroups, controller: :mailgroups











end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #        :recoverable, :rememberable, :trackable, :validatable, :registerable
  devise :ldap_authenticatable, :rememberable, :trackable

	has_and_belongs_to_many :mailgroups
  #has_and_belongs_to_many :lists, through: :mailgroups


  scope :companies,  -> { where("firstname is NULL and lastname is NULL") }

  def lastname
    # self[:lastname] || self[:company]
    self[:lastname].present? ? self[:lastname] : self[:company]
  end


  def self.searched(term)
    
    Rails::logger.debug("entered self.searched, term = " + term)

    #term.gsub!(/[^0-9A-Za-z\-+ ]/, '')
    term.gsub!(/[^[:alpha:] @.[0-9]-\\']/, "")
    t = term.split.join(":* & ") + ":*"  # pipe symbol means OR, & symbol means AND

    u = SearchIndex.connection.select_all("
        SELECT ts_rank_cd(document, query, 1) AS rank, si.id
        FROM search_indices si, to_tsquery(unaccent('#{t}')) query
        WHERE query @@ document
        order by rank
    ")

    # now stuff the id's into an array
    # i = u.map{ |x| User.find(x).id }
    ids = []
    u.map do |i|
        i.select do |k,v|
            ids << v if k == 'id'
        end
    end

    # now make an activerecord relation for the object 'User'
    # and return the ActiveRecord::Relation
    # this is equal to select * from users where id in ids.   --> ids is an Array
    self.where(id: ids)

  end


  def get_ad_display_name
    display_names = Devise::LDAP::Adapter.get_ldap_param(self.login, "displayname")
    (display_names.nil?) || display_names.empty? ? self.login : display_names.first
  end


  private

  # def get_groups
  #   Devise::LDAP::Adapter.get_ldap_param(self.login, "memberOf") || []
  # end

  
end



  #accepts_nested_attributes_for :title, :firstname, :lastname, :company, :street, :appendix, :city, :zip, :country, :fax, :phone, :phone2, :email, :email2, :gender, :initials, :language, :memo, :prio, :mailgroups, :function, :created_by, :updated_by
  #validates_uniqueness_of :user_id, scope: :mailgroup_id
  #scope :searched, ->(term) { where("created_at < ?", term) }

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #caches_page :index
  before_action :authenticate, except: [:index, :search_for, :show, :sample, :print, :get_by_ids, :append, :remove]
  before_action :set_user, only: [:show, :edit, :copy, :update, :destroy, :print, :remove]
  before_action :set_term, only: [:index]
  before_action :set_sort, only: [:index, :show]

  helper_method :sort_column, :sort_direction

  protect_from_forgery except: [:create]

  # GET /users
  # GET /users.json
  def index
    # @users = User.order(sort_column).order(sort_direction).paginate(page: params[:page])
    # this is also used for searches !!!!
    @c ||= "lastname"

    if @term.present?
      @users = User.searched(@term).order(@c + ' ' + @d).paginate(page: params[:page])
    elsif params[:termphone].present?
      phone = params[:termphone].gsub(/[\+\s+]/, "")
      @users = User.where('replace(phone, \' \', \'\') ILIKE ?', '%' + phone + '%' ).order(@c + ' ' + @d).paginate(page: params[:page])
    else
      @users = User.order(@c + ' ' + @d).paginate(page: params[:page])
    end

    respond_to do |format|
        format.html # will call index.html.erb
        format.json { render json: @users }
        #format.js   # will call index.js.coffee
    end
  end


  # GET /users/1
  # GET /users/1.json
  def show
    @c ||= "name"

    # if @term.present?
    #   @users = User.searched(@term).order(@c + ' ' + @d).paginate(page: params[:page])
    # else 
    #   @users = User.order(@c + ' ' + @d).paginate(page: params[:page])
    # end
    
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  # GET /users/new
  def new
    @user = User.new
    @user.created_by = current_user.login
    @user.created_at = Time.now
  end


  def copy
    new_user = @user.dup    #duplicate !
    new_user.salutation = nil
    new_user.title = nil
    new_user.lastname = nil
    new_user.firstname = nil
    new_user.email = nil
    new_user.gender = nil
    new_user.created_by = current_user.login
    new_user.created_at = Time.now
    @user = new_user
    render :edit
  end

  def get_by_ids
    ids = params['ids'].split(',').map{|id| id.to_i}
    users = User.where("id IN (?)", ids)
    respond_to do |format|
      format.json { render json: users.as_json }
    end
  end


  # GET /users/1/edit
  def edit
    #params.require(:user).permit(:updated_by, :updated_at)
    @user.updated_by = current_user.login
    @user.updated_at = Time.now  
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.updated_by = current_user.login
    @user.updated_at = Time.now
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def sample
    allids = User.pluck(:id)
    @user  = User.find(allids.sample)
    respond_to do |format|
      format.html { redirect_to(@user)  } 
      format.json { render json: @user }
    end
  end

  def print
    respond_to do |format|
      format.js
    end
  end


  # append a MAILGROUP to a user
  def append
    @mailgroup = Mailgroup.find(params[:mailgroup_id])  # this param comes from hidden tag, not from url!
    @user = User.find(params[:user_id])
    respond_to do |format|
      if @mailgroup.users.append(@user)   # this is a collection-proxy method  ::  http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-append
        format.html { redirect_to @user, notice: 'Mailgroup was successfully added.' }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # remove a MAILGROUP from a user
  def remove
    @mailgroup = Mailgroup.find(params[:mailgroup_id])  # this param comes from hidden tag, not from url!
    @user = User.find(params[:id])
    @mailgroup.users.delete(@user)
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully removed from mailgroup.' }
      format.json { head :no_content }
      format.js
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.


    def set_user
      @user = User.find(params[:id])
    end


    def set_term
      @term = params[:term]
    end


    def set_sort
      @c = sort_column
      @d = sort_direction
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:salutation, :title, :firstname,
        :lastname, :function, :company, :appendix, :street, :city, :zip,
        :country, :fax, :phone, :phone2, :email, :email2, :gender, :sakkrole, :language, :memo, :prio, :created_by, :created_at, :updated_by, :updated_at)
    end


end

app/helpers/users_helper.rb
module UsersHelper

  def check_box(user, show_check)
    if show_check
      content_tag(:td) do
        content_tag(:div, class: "checkbox checkbox-primary") do
          check_box_tag("user[#{user.id}]", user.id, true) +   # wegen '+' : http://stackoverflow.com/questions/4205613/rails-nested-content-tag
          content_tag(:label)
        end
      end
    end
  end






end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

<div class="col-md-6">

  <div class="control-group row">
    <%= f.label :id, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-3">
      <%= f.text_field :id, class: 'form-control', readonly: true  %>
    </div>
    <%= error_span(@user[:id]) %>
  </div>
  <div class="control-group row">
    <%= f.label :salutation, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-3">
      <%= f.text_field :salutation, class: 'form-control input-small' %>
    </div>
    <%= error_span(@user[:salutation]) %>
  </div>
  <div class="control-group row">
    <%= f.label :title, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-4">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <%= error_span(@user[:title]) %>
  </div>
  <div class="control-group row">
    <%= f.label :firstname, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :firstname, class: 'form-control' %>
    </div>
    <%= error_span(@user[:firstname]) %>
  </div>
  <div class="control-group row">
    <%= f.label :lastname, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :lastname, class: 'form-control' %>
    </div>
    <%= error_span(@user[:lastname]) %>
  </div>
  <div class="control-group row">
    <%= f.label :function, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :function, class: 'form-control' %>
    </div>
    <%= error_span(@user[:function]) %>
  </div>
  <div class="control-group row">
    <%= f.label :company, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-9">
      <%= f.text_field :company, class: 'form-control' %>
    </div>
    <%= error_span(@user[:company]) %>
  </div>
  <div class="control-group row">
    <%= f.label :appendix, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-9">
      <%= f.text_field :appendix, class: 'form-control' %>
    </div>
    <%= error_span(@user[:appendix]) %>
  </div>
  <div class="control-group row">
    <%= f.label :street, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-9">
      <%= f.text_field :street, class: 'form-control' %>
    </div>
    <%= error_span(@user[:street]) %>
  </div>
  <div class="control-group row">
    <%= f.label :city, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-9">
      <%= f.text_field :city, class: 'form-control' %>
    </div>
    <%= error_span(@user[:city]) %>
  </div>
  <div class="control-group row">
    <%= f.label :zip, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-4">
      <%= f.text_field :zip, class: 'form-control' %>
    </div>
    <%= error_span(@user[:zip]) %>
  </div>
  <div class="control-group row">
    <%= f.label :country, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :country, class: 'form-control' %>
    </div>
    <%= error_span(@user[:country]) %>
  </div>
</div>


<div class="col-md-6">
  <div class="control-group row">
    <%= f.label :fax, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :fax, class: 'form-control' %>
    </div>
    <%= error_span(@user[:fax]) %>
  </div>
  <div class="control-group row">
    <%= f.label :phone, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
    <%= error_span(@user[:phone]) %>
  </div>
  <div class="control-group row">
    <%= f.label :phone2, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :phone2, class: 'form-control' %>
    </div>
    <%= error_span(@user[:phone2]) %>
  </div>
  <div class="control-group row">
    <%= f.label :email, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <%= error_span(@user[:email]) %>
  </div>
  <div class="control-group row">
    <%= f.label :email2, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :email2, class: 'form-control' %>
    </div>
    <%= error_span(@user[:email2]) %>
  </div>
  <div class="control-group row">
    <%= f.label :gender, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-3">
      <%= f.text_field :gender, class: 'form-control' %>
    </div>
    <%= error_span(@user[:gender]) %>
  </div>
  <div class="control-group row">
    <%= f.label 'SAKK role', class: 'control-label col-lg-3' %>
    <div class="controls col-lg-3">
      <%= f.text_field :sakkrole, class: 'form-control' %>
    </div>
    <%= error_span(@user[:sakkrole]) %>
  </div>
  <div class="control-group row">
    <%= f.label :language, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-3">
      <%= f.text_field :language, class: 'form-control' %>
    </div>
    <%= error_span(@user[:language]) %>
  </div>
  <div class="control-group row">
    <%= f.label :memo, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-9">
      <%= f.text_area :memo, class: 'form-control' %>
    </div>
    <%= error_span(@user[:memo]) %>
  </div>
  <!-- div class="control-group row">
    <%= f.label :prio, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :prio, class: 'form-control' %>
    </div>
    <%= error_span(@user[:prio]) %>
  </div -->
  <!--div class="control-group">
    <%= f.label :mailgroups, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :mailgroups, class: 'form-control' %>
    </div>
    <%= error_span(@user[:mailgroups]) %>
  </div-->
  <div class="control-group row">
    <%= f.label :created_by, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :created_by, class: 'form-control', readonly: true  %>
    </div>
    <%= error_span(@user[:created_by]) %>
  </div>
  <div class="control-group row">
    <%= f.label :updated_by, class: 'control-label col-lg-3' %>
    <div class="controls col-lg-6">
      <%= f.text_field :updated_by, class: 'form-control', readonly: true   %>
    </div>
    <%= error_span(@user[:updated_by]) %>
  </div>
</div>

<div class="panel-btn-group">
  <%= f.button 'Update', class: 'btn btn-primary spacer-medium' do %>
    <i class="fa fa-floppy-o"></i>Save
  <% end %>

  <!-- %= f.submit 'Update', class: 'btn btn-primary spacer-medium' % -->

  <%= link_to '<i class="fa fa-user"></i> Users'.html_safe,
      users_path, class: 'btn btn-default spacer-medium' %>

 
  <%= link_to '<i class="fa fa-ban"></i> Cancel'.html_safe,
      :back, class: 'btn btn-default  spacer-medium' %>

</div>
<% end %>

<div class="col-lg-12">
<p class='iv'><%= "#{__FILE__}" %></p>
</div>

app/views/users/_mailgroup_users.html.erb
<%- model_class = User -%>
<% javascript_include_tag "append.js" %>

<div class="page-header col-lg-12">
  <span class="dim"></span><h2><%= content_tag(:i, nil, class: 'fa fa-user') + "  #{@mailgroup.users.count(:id)}"  %>
  Assigned user(s)</h2>
</div>

<table class="table table-striped fadeactions users">
  <%= render partial: 'users/user_header', locals: {show_check: true} %>
  <tbody>
      <%= render partial: 'users/user', collection: @mailgroup.users.order(@c + ' ' + @d), as: :user,
      locals: {show_check: true} %> 
  </tbody>
</table>

<% if @mailgroup.class.name == 'Mailgroup' %> <!-- ONLY SHOW APPEND WHEN NOT INTMAILGROUP  -->
  <%= form_tag append_mailgroup_users_path(@mailgroup), method: :patch, remote: true do %>
    <div class="input-group append col-md-6">

      <%= text_field_tag 'autousers', '', size: 50, class: 'form-control' %>
      <%= hidden_field_tag 'user_id', 'dummy' %>

      <span class="input-group-btn append">
        <button class="btn btn-default" type="submit">Append</button>
      </span>
    </div>
  <% end %>
<% end %>

<%= content_tag(:div, "partial users/user" , class: 'iv col-lg-12') %>
<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/users/_print.html.erb
<div class="modal fade" id="modprint_user">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h2 class="modal-title"><i class="fa fa-print"></i>&nbsp Print</h2>
      </div>

        <div class="modal-body">

        <div class="page-header col-lg-12">
          <h1><%= content_tag(:i, nil, class: 'fa print') %>
            <span class="dim"></span><%= "#{@user.firstname} #{@user.lastname}" %> 
          </h1>
        </div>


        <ul class="print-options">

          <li> <!--   BADGE  -->
            <%= link_to(content_tag(:i, nil, class: 'fa fa-tag') + "Print badge", 
                  "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+USER+BADGE&rs:Command=Render&rs:Format=PDF&UserID=#{@user.id}",
                  data: {toggle: "tooltip", title: "Print single badge", placement: 'right'},
                  target: '_blank',
                  class: 'btn btn-default fixed-width'
                )
             %>
          </li>
          
          <li> <!--   LABEL  -->
            <%= link_to content_tag(:i, nil, class: 'fa fa-print') + "Print label",
                  "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+USER+LABEL&rs:Command=Render&rs:Format=PDF&UserID=#{@user.id}",
                  data: {toggle: "tooltip", title: "Print single label", placement: 'right'},
                  class: 'btn btn-default fixed-width'
             %>
          </li>

          <li> <!--   USER DETAILS  -->
            <%= link_to content_tag(:i, nil, class: 'fa fa-print') + "Print user details",
                  # "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+USER+OVERVIEW&rs:Command=Render&rs:Format=PDF&UserID=#{@user.id}",
                  "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+USER+DETAILS&rs:Command=Render&rs:Format=PDF&UserID=#{@user.id}",
                  data: {toggle: "tooltip", title: "User details and group memberships", placement: 'right'},
                  class: 'btn btn-default fixed-width'
             %>
          </li>

        </ul>
        
       <div class="modal-footer">

      <%= link_to content_tag(:i, "", class: "fa fa-close") + "Close",
                  "",
                  class: "btn btn-default",
                  data: { dismiss: "modal"}
      %>

        </div><!-- /.modal-footer -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/_search_for.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <h2>Search for <i><%= params[:term]%>:</i></h2>
  <p>Note: search is case insensitive</p>

</div><!-- h1 -->

<%= render partial: 'userlist' %>

<p class='iv'><%= "#{__FILE__}" %></p>

app/views/users/_user.html.erb
<!-- No loop is needed when rendering this partial, since we pass a collection -->

<%= content_tag_for(:tr, user) do %>
  <td class="dim"><%= user.id %></td>
  <%= check_box(user, show_check) %>
  <td><%= user.lastname %></td>
  <td><%= user.firstname %></td>
  <td><%= user.function %></td>
  <td><%= user.company %></td>
  <td><%= user.appendix %></td>
  <td><%= user.city %></td> 
  <td class="fadeactions col-md-2">

    <%= link_to(content_tag(:i, nil, class: 'fa fa-user'), user_path(user),
          data: {toggle: "tooltip", title: "User details and assigned groups", placement: 'top'}) 
     %>

    <%= link_to( content_tag(:i, nil, class: 'fa fa-envelope-o'), "mailto:#{user.email}",
          data: {toggle: "tooltip", title: "Email to", placement: 'top'}) if user.email?
     %>

    <%= link_to(content_tag(:i, nil, class: 'fa fa-pencil'), edit_user_path(user),
          data: {toggle: "tooltip", title: "Edit user", placement: 'top'}) if mutation?
     %>

    <%= unless @mailgroup.nil?
          link_to content_tag(:i, nil, class: 'fa fa-minus-square-o'),
                  remove_mailgroup_user_path(@mailgroup, user),
                  method: :delete,
                  remote: true,
                  data: { confirm: "Sure to remove #{user.firstname} #{user.lastname} from #{@mailgroup.name} ?",
                           toggle: "tooltip", title: "Remove user from group", placement: 'top'} if @mailgroup.query.nil?
        end
     %>

    <%= link_to(content_tag(:i, nil, class: 'fa fa-trash-o'),
      user_path(user),
      method: :delete,
      remote: true,
      data: { confirm: "Sure to delete #{user.firstname} #{user.lastname}",
               toggle: "tooltip", title: "Delete user", placement: 'top'
        }) if !defined? @mailgroup and mutation?
    %>

  </td>
<% end %>

app/views/users/_user_header.html.erb
<%- model_class = User -%>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

<col width="5%"  />
<% if show_check %>
    <col width="3%"  />
<% end %>    
<col width="10%" />
<col width="15%" />
<col width="15%" />
<col width="15%" />
<col width="15%" />
<col width="12%" />
<col width="10%" />


<thead>
  <tr>
    <th class="dim"><%= model_class.human_attribute_name(:id) %></th>
    <% if show_check %>
    <th><%= 
        content_tag(:div, class: "checkbox checkbox-primary") do
          check_box_tag('select_all', 'yes', true) +   # wegen '+' : http://stackoverflow.com/questions/4205613/rails-nested-content-tag
          content_tag(:label)
        end %>
    </th>
    <% end %>
    <th><%= sortable("lastname") %></th>
    <th><%= sortable("firstname") %></th>
    <th><%= sortable("function") %></th>
    <th><%= sortable("company") %></th>
    <th><%= sortable("appendix") %></th>
    <th><%= sortable("city") %></th>
    <th class="dim"><%=t '.actions', default: t("helpers.actions") %></th>
  </tr>
</thead>

app/views/users/index.html.erb
<%- model_class = User -%>



<div class="page-header col-lg-3">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class="col-lg-3 spacer-button">
	<%= link_to 'New User',
	            new_user_path,
	            class: 'btn btn-primary' if mutation?
	 %>
  <%= link_to 'Pick a sample', 
			    		sample_user_path,
			        data: {toggle: "tooltip", title: "Go to a randomly selected user", placement: 'top'},
				 			class: 'btn btn-primary' 
   %>
</div>

<div class="col-lg-4 spacer-button">
	<%= form_tag(users_path, method: "get") do %>
	  <div class="input-group search">
	    <span class="input-group-addon" id="basic-addon1"><i class="fa fa-file-text-o"></i></span>
	    <input type="text" class="form-control" placeholder="Search for term in all fields" name="term">
	    <span class="input-group-btn">
	      <button class="btn btn-default" type="submit">Go!</button>
	    </span>
	  </div>
	<% end %>
	<%= form_tag(users_path, method: "get") do %>
	  <div class="input-group search-tel spacer-small">
	  	<span class="input-group-addon" id="basic-addon2"><i class="fa fa-phone"></i></span>
	    <input type="text" pattern="[ +0-9]*" class="form-control" min="0" step="1" placeholder="Search phone number" name="termphone">
	    <span class="input-group-btn">
	      <button class="btn btn-default" type="submit">Go!</button>
	    </span>
	  </div>
	<% end %>

</div>


<% if @term.present? %>
	<div class="col-lg-12">
		<%= content_tag(:h3, "Search results for ")  %>
		<%= content_tag(:i, content_tag(:h2, "'#{@term}'", class: "strong")) %>
	</div>
<% end %>

<%= render partial: 'userlist' %>


<div class='col-lg-12 iv'><%= "#{__FILE__}" %></div>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

<p class='iv'><%= "#{__FILE__}" %></p>