config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}  
  
  root to: 'users#index'  


  get 'sample_user', to: 'users#sample'     # it's not in resources since we don't have an id when selecting
  get 'users/get_by_ids' => 'users#get_by_ids'
  get 'lists/own'

  resources :users do

        member do   # member is for passing :id instead of :user_id
          get   'print' #,  to: 'users#print',  as: 'print'
          get   'copy'  #,  to: 'users#edit',   as: 'copy'
        end

        resources :mailgroups do      
          patch 'append',    to: 'users#append',  on: :collection    # append a MAILGROUP to a user
          member do
            delete 'remove', to: 'mailgroups#remove'
          end
        end

  end



  resources :mailgroups do

    member do
      get 'mailto'
      get 'print'
    end

    collection do
      get   'search_for', to: 'mailgroups#search_for',  as: 'search'
    end

    resources :users do
      patch 'append',     to: 'mailgroups#append', on: :collection   # append a USER to a mailgroup
      member do
        delete 'remove',  to: 'users#remove'    # remove USER from a mailgroup
      end
    end

  end


  resources :lists do

    resources :mailgroups do      
      patch 'append',     to: 'lists#append',  on: :collection    # append a MAILGROUP to a user
      member do  
        delete 'remove',  to: 'mailgroups#remove_list'
      end
    end

  end


  resources :intlists,      path: :lists,      controller: :list
  resources :intmailgroups, path: :mailgroups, controller: :mailgroups











end

app/models/mailgroup.rb
class Mailgroup < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_and_belongs_to_many :lists
  has_many :trial_contacts


  validates :name, uniqueness: true, presence: true
  #validates :query, presence: false

  scope :searched,    -> (term) { where("name ILIKE '%#{term}%'") if term.present? }
  scope :is_robinson, -> { where('robinson_id is not NULL') }
  # scope :regular,     -> { where('query is NULL') }



end

app/controllers/mailgroups_controller.rb
class MailgroupsController < ApplicationController

  require 'mailgroups_helper'
  #caches_page   :index
  # rescue_from ActionController::ParameterMissing, with: :param_missing


  before_action :authenticate, except: [:index, :search_for, :show, :search, :mailto, :print, :append, :remove]
  before_action :set_mailgroup, only:  [:show, :edit, :update, :destroy, :mailto, :print, :remove, :remove_list, :count]
  before_action :set_term, only: [:index]
  before_action :set_sort, only: [:index, :show]

  helper_method :sort_column, :sort_direction

  respond_to :html, :json, :js

  # GET /mailgroups
  # GET /mailgroups.json
  def index
    @c ||= 'name'
    @mailgroups  = Mailgroup.searched(@term).order(@c + ' ' + @d).paginate(page: params[:page])
    #respond_with (@mailgroups)
    respond_to do |format|
        format.html # will call index.html.erb
        format.json { render json: @mailgroups }
        #format.js   # will call index.js.coffee
    end    
  end


  # GET /mailgroups/1
  # GET /mailgroups/1.json
  def show
    @c ||= 'lastname'
  end

  # GET /mailgroups/new
  def new
    @mailgroup = Mailgroup.new
    @mailgroup.created_by = current_user.login
    @mailgroup.created_at = Time.now
  end

  # GET /mailgroups/1/edit
  def edit
  end

  # POST /mailgroups
  # POST /mailgroups.json
  def create
    @mailgroup.created_by = current_user.login
    @mailgroup.created_at = Time.now
    respond_to do |format|
      if @mailgroup.save
        format.html { redirect_to @mailgroup, notice: 'Mailgroup was successfully created.' }
        format.json { render :show, status: :created, location: @mailgroup }
      else
        format.html { render :new }
        format.json { render json: @mailgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mailgroups/1
  # PATCH/PUT /mailgroups/1.json
  def update
    # @mailgroup.updated_by = current_user.login
    # @mailgroup.updated_at = Time.now
    # @query = get_query(params)
    # logger.debug "in def update, query=#{@query}"
    mp = mailgroup_params.fetch_values('trialcode', 'role', 'country')
    logger.debug "UPDATE intmailgroup, intparams : #{mp}"
    if mp.present?
      # @mailgroup.users.delete_all
      # @mailgroup.type = mailgroup_params[:type]
      @mailgroup = @mailgroup.becomes!(Intmailgroup)
      logger.debug "UPDATE after becomes! mailgroup.type = #{@mailgroup.type}"
      # @mailgroup.query = @query
    else
      logger.debug "UPDATE else (query not present), mailgroup_params = #{mailgroup_params}"
      @mailgroup = @mailgroup.becomes!(Mailgroup)
    end
    respond_to do |format|
    if @mailgroup.update(mailgroup_params)
      format.html { redirect_to @mailgroup, notice: 'Mailgroup was successfully updated.' }
      format.json { render :show, status: :ok, location: @mailgroup }
    else
      format.html { render :edit }
      format.json { render json: @mailgroup.errors, status: :unprocessable_entity }
    end
    end

    # rescue ActiveRecord::StatementInvalid => error
    # respond_to do |format|
    #   format.html { render :edit, notice: 'Mailgroup was successfully updated.'  }
    #   format.json { render json: @mailgroup.errors, status: :unprocessable_entity }
    # end
    logger.debug "in mailgroups_controller, mailgroup_params= #{mailgroup_params}. \n update exit"

  end

  # DELETE /mailgroups/1
  # DELETE /mailgroups/1.json
  def destroy
    @mailgroup.destroy
    respond_to do |format|
      format.html { redirect_to mailgroups_url, notice: 'Mailgroup was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end


  def append
    @user      = User.find(params[:user_id])
    @mailgroup = Mailgroup.find(params[:mailgroup_id])
    respond_to do |format|
      if @user.mailgroups.append(@mailgroup) # append: CollectionProxy method --> http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-append
        format.html { redirect_to @mailgroup, notice: 'Mailgroup was successfully added to user.' }
        format.json { render :show, status: :created, location: @mailgroup }
        format.js
      else
        format.html { render :new }
        format.json { render json: @mailgroup.errors, status: :unprocessable_entity }
      end
    end
  end 

  # remove a USER from a mailgroup
  def remove
    # lets get the parameters from the url. we get them from the hash 'params'

    @user = User.find(params[:user_id])
    @user.mailgroups.delete(@mailgroup)

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Mailgroup was successfully removed.' }  #reload this page after deletion
      format.json { head :no_content }
      format.js
    end
  end


  def remove_list
    # remove a mailgroup from list
    # lets get the parameters from the url. we get them from the hash 'params'
    @list = List.find(params[:list_id])
    @list.mailgroups.delete(@mailgroup)

    respond_to do |format|
      #format.html { redirect_to :back, notice: 'Mailgroup was successfully removed from list.' }  #reload this page after deletion
      #format.json { head :no_content }
      format.js
    end
  end



  def mailto
    respond_to do |format|
        format.js
    end
  end


  def print
    respond_to do |format|
        #format.html
        format.js
    end    
  end



  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

  protected


      # Never trust parameters from the scary internet, only allow the white list through.
    def mailgroup_params
      if params["mailgroup"].present?
        params.require(:mailgroup).permit(:name, :memo, :trialcode, :query, :country, :role, :type)
      elsif params["intmailgroup"].present?
        params.require(:intmailgroup).permit(:name, :memo, :trialcode, :query, :country, :role, :type)
      else
        nil
      end
    end

  

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_mailgroup
      logger.debug "mailgroups_controller set_mailgroup enter"
      @mailgroup = Mailgroup.find(params[:id])
      logger.debug "mailgroups_controller set_mailgroup mailgroup=#{@mailgroup.name}"
      logger.debug "mailgroups_controller set_mailgroup exit"      
    end

    def set_term
      @term = params[:term]
    end

    def set_sort
      @c = sort_column
      @d = sort_direction; @d ||= 'asc'
    end

end

app/helpers/mailgroups_helper.rb
module MailgroupsHelper

end

app/views/mailgroups/_bccrecps.html.erb
<div id="mailgroupmails"  class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h2 class="modal-title"><i class="fa fa-envelope"></i>&nbsp Emails of group <%= @mailgroup.name %></h2>Triple click to select all emails, copy to clipboard and paste into BCC field in Outlook.
      </div>

        <div class="modal-body">
          <div id="modal-results" class="well">
          </div>
        
        </div>

        <div class="modal-footer">
          
        <!--  <%= link_to content_tag(:i, '', class: "fa fa-copy") + "Copy to clipboard",
                      "",
                      class: 'btn btn-default',
                      id: "c2c"
          %> -->


          <%= link_to content_tag(:i, '', class: "fa fa-close") + "Close",
                      "",
                      class: 'btn btn-default',
                      data: { dismiss: 'modal'}
          %>


        </div><!-- /.modal-footer -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/mailgroups/_form.html.erb
<%= form_for @mailgroup, html: { class: "form-horizontal mailgroup" } do |f| %>

    <% if @mailgroup.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@mailgroup.errors.count, "error") %> prohibited this mailgroup from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @mailgroup.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group row">
    <%= f.label :id, class: 'control-label col-lg-1 dim' %>
    <div class="controls col-lg-6">
      <%= f.text_field :id, class: 'form-control', readonly: true %>
    </div>
    <%= error_span(@mailgroup[:id]) %>
  </div>
  <div class="control-group row">
    <%= f.label :name, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-6">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <%= error_span(@mailgroup[:name]) %>
  </div>
  <div class="control-group row">
    <%= f.label :memo, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-6">
      <%= f.text_field :memo, class: 'form-control' %>
    </div>
    <%= error_span(@mailgroup[:memo]) %>
  </div>
  <div class="control-group row">
    <%= f.label :trialcode, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-6">
      <%= f.text_field :trialcode, class: 'form-control' %>
    </div>
    <%= error_span(@mailgroup[:trialcode]) %>
  </div>
  <div class="control-group row">
    <%= f.label :role, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-6">
      <%= f.text_field :role, class: 'form-control' %>
    </div>
    <%= error_span(@mailgroup[:trialcode]) %>
  </div>

  <div class="control-group row">
    <%= f.label :query, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-4">
      <%= f.text_field :query, class: 'form-control' %>
    </div>
    <%= error_span(@mailgroup[:query]) %>
  </div>

  <div class="control-group row">
    <%= f.label :country, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-4">
      <%= f.text_field :country, class: 'form-control' %>
    </div>
    <%= error_span(@mailgroup[:country]) %>
  </div> 


  <div class="control-group row">
    <%= f.label :created_by, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-6">
      <%= f.text_field :created_by, class: 'form-control', readonly: true  %>
    </div>
    <%= error_span(@mailgroup[:created_by]) %>
  </div>
  <div class="control-group row">
    <%= f.label :updated_by, class: 'control-label col-lg-1' %>
    <div class="controls col-lg-6">
      <%= f.text_field :updated_by, class: 'form-control', readonly: true %>
    </div>
    <%= error_span(@mailgroup[:updated_by]) %>
  </div>


  <!-- %= f.submit '', class: 'btn btn-primary spacer-medium' % -->
  <%= f.button 'Update', class: 'btn btn-primary spacer-medium' do %>
    <i class="fa fa-save"></i> Save
  <% end %> 


  <%= link_to t('.back', default: t("helpers.links.cancel")),
            :back, class: 'btn btn-default spacer-medium' %>

<% end %>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/mailgroups/_list_mailgroups.html.erb
<%- model_class = Mailgroup -%>

<div class="page-header col-lg-12">
  <span class="dim"></span><h2><%= content_tag(:i, nil, class: 'fa fa-users') %>
  Assigned groups</h2>
</div>

<table class="table table-striped fadeactions mailgroups">
  <thead>
    <tr>
      <th class="dim"><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:trialcode) %></th>
      <th># Users with Email</th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>

    <%= render partial: 'mailgroups/mailgroup_append_list', collection: @list.mailgroups, as: :mailgroup %>

  </tbody>
</table>

<% if (mutation? == @list.admin) and @list.query.nil? %>
  <!-- append  a MAILGROUP to the list -->
  <%= form_tag append_list_mailgroups_path(@list), method: :patch, remote: true do %>
    <div class="input-group append col-lg-6">

      <%= text_field_tag   'autogroups',   '', size: 75, class: 'form-control' %>
      <%= hidden_field_tag 'mailgroup_id', 'dummy' %>

      <span class="input-group-btn append">
          <button class="btn btn-default" type="submit">Append</button>
      </span>
    </div>
  <% end %>
<% end %>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/mailgroups/_mailgroup.html.erb
<!-- No loop is needed when rendering this partial -->

<%= content_tag_for(:tr, mailgroup) do %>
  <td class="dim"><%= mailgroup.id %></td>
  <td><%= mailgroup.name %></td>
  <td><!-- in intmailgroup the zahnrad is rendered here --></td>
  <td><%= mailgroup.trialcode %></td>
  <td><%= mailgroup.role %></td>
  <td><%= mailgroup.country %></td>
  <td><%= mailgroup.users.count(:id) %></td>
  
  <td class="fadeactions col-md-2">

    <%= link_to(content_tag(:i, nil, class: 'fa fa-group loaderlink' ), mailgroup_path(mailgroup),
          data: {toggle: "tooltip", title: "Group details and members", placement: 'top'})
     %>


    <%= link_to(content_tag(:i, nil, class: 'fa fa-pencil'), edit_mailgroup_path(mailgroup),
          data: {toggle: "tooltip", title: "Edit mailgroup", placement: 'top'}) if mutation?
     %>

    <%= link_to content_tag(:i, nil, class: 'fa fa-minus-square-o'),
                remove_user_mailgroup_path(@user, mailgroup),
                method: :delete, remote: true,
                data: { confirm: "Sure to remove #{mailgroup.name} from #{@user.firstname} #{@user.lastname}?",
                          title: "Please confirm",
                         toggle: "tooltip", title: "Remove group from user", placement: 'top'
                      } if defined? @user
     %>

    <%= link_to(content_tag(:i, nil, class: 'fa fa-trash-o'),
          mailgroup_path(mailgroup),
          method: :delete, remote: true,
          data: { confirm: "Sure to delete #{mailgroup.name}?  \nIMPORTANT: Assigned users won't be deleted",
                   toggle: "tooltip", title: "Delete mailgroup", placement: 'top'
        }) if !defined? @user and mutation?
    %>
  </td>
<% end %>

app/views/mailgroups/_mailgroup_append_list.html.erb

<!--

  Adds MAILGROUPS to predefined LISTS

-->

<%= content_tag_for(:tr, mailgroup) do %>


  <td class="dim"><%= mailgroup.id %></td>
  <td><%= mailgroup.name %></td>
  <td><%= mailgroup.trialcode %></td>
  <td><%= mailgroup.users.count(:id) %></td>
  <td class="fadeactions col-md-2">

    <%= link_to(content_tag(:i, nil, class: 'fa fa-group' ), mailgroup_path(mailgroup),
          data: {toggle: "tooltip", title: "Users", placement: 'top'})
     %>

    <%= link_to(content_tag(:i, nil, class: 'fa fa-pencil'), edit_mailgroup_path(mailgroup),
          data: {toggle: "tooltip", title: "Edit mailgroup", placement: 'top'}) 
     %>
     

    <%= link_to(content_tag(:i, nil, class: 'fa fa-minus-square-o'),
        remove_list_mailgroup_path(@list, mailgroup),
          method: :delete,
          remote: true,
          data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')),
            toggle: "tooltip", title: "Remove mailgroup from list", placement: 'top'
          }) if mutation? and @list.query.nil?
     %>

  </td>
<% end %>

app/views/mailgroups/_mailgroup_header.html.erb
<%- model_class = Mailgroup -%>


<col width="5%"  /> <!-- id  			 -->
<col width="15%" /> <!-- name      -->
<col width="5%"  /> <!-- zahnrad   -->
<col width="15%" /> <!-- trialcode -->
<col width="15%" /> <!-- role      -->
<col width="15%" /> <!-- country   -->
<col width="10%" /> <!-- count     -->
<col width="20%" /> <!-- actions   -->

<thead>
  <tr>
    <th class="dim"><%= model_class.human_attribute_name(:id) %></th>
    <th class="loaderlink"><%= sortable("name") %></th>
    <th><%= model_class.human_attribute_name(:type) %></th>
    <th><%= model_class.human_attribute_name(:trialcode) %></th>
    <th><%= model_class.human_attribute_name(:role) %></th>
    <th><%= model_class.human_attribute_name(:country) %></th>
    <th class="loaderlink"><%= sortable("user_count", "# Users") %></th>
    <th><%=t '.actions', default: t("helpers.actions") %></th>
  </tr>
</thead>

app/views/mailgroups/_mailgrouplist.html.erb
<%- model_class = Mailgroup -%>

<div class="row col-lg-8">
<%= will_paginate @mailgroup, renderer: BootstrapPagination::Rails %>
</div>

<table class="table table-striped fadeactions mailgroups">
  <thead class="grad">
    <tr>
      <td class="dim"><%= model_class.human_attribute_name(:id) %></td>
      <td><%= sortable('name') %></td>
      <td><%= model_class.human_attribute_name(:trialcode) %></td>
      <td># Users</td>
      <td><%=t '.actions', default: t("helpers.actions") %></td>
    </tr>
  </thead>
  <tbody>

    <%= render partial: "mailgroup", collection: @mailgroups, as: :mailgroup %>

  </tbody>
</table>

<div class="row col-lg-12">
  <%= link_to t('.new', default: t("helpers.links.new")),
              new_mailgroup_path,
              class: 'btn btn-primary' if mutation? %>

  <%= link_to t('.back', default: t("helpers.links.back")),
              :back,
              class: 'btn btn-default' %>
</div>


<div class="row col-lg-8">
<%= will_paginate @mailgroup, renderer: BootstrapPagination::Rails %>
</div>


app/views/mailgroups/_print.html.erb


<div class="modal fade" id="modprint_group" tabindex="-1" role="dialog" aria-labelledby="PrintModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h2 class="modal-title"><i class="fa fa-print"></i>&nbsp Print</h2>
      </div>
      <div class="modal-body">

        <div class="page-header col-lg-12">
          <h1><%= content_tag(:i, nil, class: 'fa print') %>
            <span class="dim"></span><%= "#{@mailgroup.name}" %>
          </h1>
        </div>


        <ul class="print-options">
          <li>
            <%= link_to(content_tag(:i, nil, class: 'fa fa-tag left') + "Print badges",
                  "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+GROUP+BADGES&rs:Command=Render&rs:Format=PDF&GroupID=#{@mailgroup.id}",
                  data: {toggle: "tooltip", title: "Print badges for group members", placement: 'right'},
                  target: '_blank',
                  class: 'btn btn-default fixed-width'
                )
             %>
          </li>

          <li>
            <%= link_to content_tag(:i, nil, class: 'fa fa-print left') + "Print labels",
                  "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+GROUP+LABELS&rs:Command=Render&rs:Format=PDF&GroupID=#{@mailgroup.id}",
                  data: {toggle: "tooltip", title: "Print labels for group members", placement: 'right'},
                  target: '_blank',
                  class: 'btn btn-default fixed-width'
             %>
          </li>

          <li>
            <%= link_to content_tag(:i, nil, class: 'fa fa-file-text left') + "Attendance list",
                  "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+ATTENDANCE+LIST&rs:Command=Render&rs:Format=Word&GroupID=#{@mailgroup.id}",
                  data: {toggle: "tooltip", title: "Attendance list (as Word)", placement: 'right'},
                  target: '_blank',
                  class: 'btn btn-default fixed-width'
             %>
          </li>

          <li>
            <%= link_to content_tag(:i, nil, class: 'fa fa-table left') + "Excel list",
                  "http://sakkreports.siak.ch/ReportServer/Pages/ReportViewer.aspx?%2fSERVICES%2fADDRESSES%2fR+GROUP+LIST&rs:Command=Render&rs:Format=Excel&GroupID=#{@mailgroup.id}",
                  data: {toggle: "tooltip", title: "General list (as Excel)", placement: 'right'},
                  target: '_blank',
                  class: 'btn btn-default fixed-width'
             %>
          </li>
        </ul>
      </div>  <!-- /.modal-body --> 
      <div class="modal-footer">
          <%= link_to content_tag(:i, '', class: "fa fa-close") + "Close",
                      "",
                      class: 'btn btn-default',
                      data: { dismiss: 'modal'}
          %>
      </div><!-- /.modal-footer -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


app/views/mailgroups/_user_mailgroups.html.erb
<%- model_class = Mailgroup -%>
<% javascript_include_tag 'append.js' %>

<div class="page-header col-lg-12">
  <span class="dim"></span>
  <h2><%= content_tag(:i, nil, class: 'fa fa-users') + " #{@user.mailgroups.count}" %>
          assigned groups</h2>
</div>


<table class="table table-striped fadeactions mailgroups">
  <%= render partial: 'mailgroups/mailgroup_header' %>
  <tbody>
    <%= render partial: "mailgroups/mailgroup", 
        collection: @user.mailgroups.order(@c + ' ' + @d), as: :mailgroup
     %>
  </tbody>
</table>



<div class="row col-lg-6">
  <!-- append  a MAILGROUP to the user -->
  <%= form_tag append_user_mailgroups_path(@user), method: :patch, remote: true do %>
    <div class="input-group append">

      <%= text_field_tag 'autogroups', '', size: 75, class: 'form-control' %>
      <%= hidden_field_tag 'mailgroup_id', 'dummy' %>

      <span class="input-group-btn append">
        <button class="btn btn-default" type="submit">Append</button>
      </span>
    </div>
  <% end %>
</div>

<%= content_tag(:div, "partial mailgroups/mailgroup" , class: 'iv col-lg-12') %>
<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/mailgroups/edit.html.erb
<%- model_class = Mailgroup -%>
<div class="page-header">
  <h1><!--%=t '.title', :default => [:'helpers.titles.edit', '%{model}'], :model => model_class.model_name.human.titleize % -->
  <%= @mailgroup.name %>
  <%= content_tag(:i, nil, class: 'fa fa-pencil') %>

  </h1>
</div>
<%= render :partial => 'form' %>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>
	

app/views/mailgroups/index.html.erb
<%- model_class = Mailgroup -%>

<div class="page-header col-lg-3">
  <h1>Groups</h1>
</div>

<div class="col-lg-3 spacer-button">
    <%= link_to 'New Group',
                new_mailgroup_path,
                class: 'btn btn-primary' if mutation?
     %>
</div>

<div class="col-lg-4 spacer-button">
  <%= form_tag(mailgroups_path, method: "get")  do %>
    <div class="input-group search">
      <input type="text" class="form-control" placeholder="Search groups" name="term">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Find</button>
      </span>
    </div>
  <% end %>
</div>


<div class="col-lg-12">
  <%= content_tag(:h3, "Search results for ") if @term.present? %>
  <%= content_tag(:i, content_tag(:h2, "'#{@term}'", class: "strong"))  if @term.present? %>
</div>


<div class="col-lg-12 row">
  <%= will_paginate @mailgroup, renderer: BootstrapPagination::Rails %>
</div>


<table class="table table-striped fadeactions mailgroups col-lg-12 fixed">
  <%= render partial: 'mailgroup_header' %>
  <tbody>
    <%= render partial: @mailgroups.order("name") %>
  </tbody>
</table>



<div class="col-lg-12">
  <%= will_paginate @mailgroup, renderer: BootstrapPagination::Rails %>
</div>

<div class="col-lg-3 spacer-button">
    <%= link_to 'New Group',
                new_mailgroup_path,
                class: 'btn btn-primary' if mutation?
     %>
   <!-- %= link_to 'Pick one', 
                sample_user_path,
                data: {toggle: "tooltip", title: "Go to a randomly selected user", placement: 'top'},
                class: 'btn btn-primary' 
     % -->
</div>

<%= content_tag(:div, "see partial 'mailgroups/mailgroup'" , class: 'iv col-lg-12') %>
<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>

app/views/mailgroups/new.html.erb
<%- model_class = Mailgroup -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

<%= content_tag(:div, "#{__FILE__}" , class: 'iv col-lg-12') %>