config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}  
  
  root to: 'users#index'  


  get 'sample_user', to: 'users#sample'     # it's not in resources since we don't have an id when selecting
  get 'users/get_by_ids' => 'users#get_by_ids'
  get 'lists/own'

  resources :users do

        member do   # member is for passing :id instead of :user_id
          get   'print' #,  to: 'users#print',  as: 'print'
          get   'copy'  #,  to: 'users#edit',   as: 'copy'
        end

        resources :mailgroups do      
          patch 'append',    to: 'users#append',  on: :collection    # append a MAILGROUP to a user
          member do
            delete 'remove', to: 'mailgroups#remove'
          end
        end

  end



  resources :mailgroups do

    member do
      get 'mailto'
      get 'print'
    end

    collection do
      get   'search_for', to: 'mailgroups#search_for',  as: 'search'
    end

    resources :users do
      patch 'append',     to: 'mailgroups#append', on: :collection   # append a USER to a mailgroup
      member do
        delete 'remove',  to: 'users#remove'    # remove USER from a mailgroup
      end
    end

  end


  resources :lists do

    resources :mailgroups do      
      patch 'append',     to: 'lists#append',  on: :collection    # append a MAILGROUP to a user
      member do  
        delete 'remove',  to: 'mailgroups#remove_list'
      end
    end

  end


  resources :intlists,      path: :lists,      controller: :list
  resources :intmailgroups, path: :mailgroups, controller: :mailgroups











end

app/views/layouts/_loader.html.erb
<div class="loader">
    <span></span>
    <span></span>
    <span></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Addman" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->


    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>

    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>

    <%= render partial: 'devise/sessions/signin' %> <!-- MODAL signin dialog , appears only when user wants to sign in -->
    <%= render partial: 'layouts/loader' %>
    </head>
  <body>

  <!-- render various modal dialogs as hidden -->

  
    
  <div class="navbar navbar-default navbar-static-top col-lg-12">
    <div class="container loaderPosition">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
    <!-- span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span  -->
      </button>
      <%= content_tag(:a, nil, class: "navbar-brand right") %>
      <%= bootstrap_flash %>

      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to content_tag(:i, '', class: "fa fa-chevron-right") + " Users",
                  users_path, class: "#{params[:controller] == 'users' ? 'active' : 'inactive'} loaderlink" %></li>

           <li><%= link_to content_tag(:i, '', class: "fa fa-chevron-right") + " Groups",
                  mailgroups_path, class: "#{params[:controller] == 'mailgroups' ? 'active' : 'inactive'} loaderlink" %></li>


          <li><%= link_to content_tag(:i, '', class: "fa fa-chevron-right") + " Lists",
                  lists_path, class: "#{params[:controller] == 'lists' ? 'active' : 'inactive'}  loaderlink" %></li>

          <li id="TT">TEST</li>


        </ul>



        <ul class="userInfo nav navbar-nav right">
          <% if user_signed_in? %>
            <!-- li><%= content_tag(:i, current_user.login) %></li -->
            <li><%= link_to content_tag(:i, '', class: "fa fa-chevron-right") + " Sign out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to content_tag(:i, '', class: 'fa fa-user') + ' ' + session[:user_display_name] %></li>
          <% else %>
            <li><%= link_to content_tag(:i, '', class: "fa fa-chevron-right") + " Sign in",
                new_user_session_path, remote: true %></li>
            <li><%= content_tag(:a, 'Not signed in') %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>


  <div class="container-main">
     
    <%= yield %>

    <footer class="spacer-large col-lg-12">
      <p>&copy; SAKK <%= Date.today.year%> | <%= APP_VERSION %></p>
    </footer>

  </div> <!-- /container -->

  </body>
</html>
 